# Generated by Django 5.1.3 on 2024-11-17 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='parent_folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanagement.folders'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='parent_folder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filemanagement.folders'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_level', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
