# Generated by Django 5.1.3 on 2024-11-18 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanagement", "0002_alter_files_parent_folder_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="files",
            old_name="parent_folder_id",
            new_name="parent_folder",
        ),
        migrations.RemoveField(
            model_name="folders",
            name="parent_folder_id",
        ),
        migrations.AddField(
            model_name="folders",
            name="parent_folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="filemanagement.folders",
            ),
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_level_read_permission", models.CharField(max_length=10)),
                ("user_level_write_permission", models.JSONField(max_length=10)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filemanagement.files",
                    ),
                ),
            ],
            options={
                "db_table": "filepermissions",
            },
        ),
    ]
