# Generated by Django 5.1.3 on 2024-11-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filemanagement", "0003_rename_parent_folder_id_files_parent_folder_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permissions",
            old_name="user_level_read_permission",
            new_name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="permissions",
            name="user_level_write_permission",
        ),
        migrations.AddField(
            model_name="permissions",
            name="user_level",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
